[package]
authors = { workspace = true }
description = "fedimint walletv2 is an on-chain bitcoin wallet module. It uses a key-value store and is not a standard HD wallet. (server)"
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-walletv2-server"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_walletv2_server"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bitcoin = { workspace = true }
erased-serde = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-server-core = { workspace = true }
fedimint-walletv2-common = { workspace = true }
futures = { workspace = true }
miniscript = { workspace = true }
rand = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tracing = { workspace = true }
