[package]
authors = { workspace = true }
description = "fedimint walletv2 is an on-chain bitcoin wallet module. It uses a key-value store and is not a standard HD wallet. (common types)"
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-walletv2-common"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_walletv2_common"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
bitcoin = { workspace = true }
fedimint-core = { workspace = true }
miniscript = { workspace = true, features = ["serde"] }
secp256k1 = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
